//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticWpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPointOfIssues
    {
        public int ProductPointOfIssuesID { get; set; }
        public int Code { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int HousNumber { get; set; }
    }
}
